spring.application.name=pukio-update-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

pukio.server.port=${SERVER_PORT}
