-- ============================================================
-- PUKIO - Sistema POS
-- Script 00: Creacion de Esquemas Múltiples (N-Capas)
-- Base de Datos: Oracle 21c XE
-- IMPORTANTE: Ejecutar este script como SYSTEM o SYS AS SYSDBA
-- ============================================================

-- 1. LIMPIEZA DE USUARIOS PREVIOS (Recreación limpia)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM ALL_USERS WHERE USERNAME = 'PUKIO_DB';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'DROP USER PUKIO_DB CASCADE'; END IF;

    SELECT COUNT(*) INTO v_count FROM ALL_USERS WHERE USERNAME = 'PUKIO_DWH';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'DROP USER PUKIO_DWH CASCADE'; END IF;
END;
/

-- 2. CREACIÓN DEL ESQUEMA TRANSACCIONAL (Capa de Datos - POS)
CREATE USER PUKIO_DB IDENTIFIED BY puk10_2024;
ALTER USER PUKIO_DB DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE TO PUKIO_DB;
GRANT CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO PUKIO_DB;
ALTER USER PUKIO_DB QUOTA UNLIMITED ON USERS;

-- 3. CREACIÓN DEL ESQUEMA ANALÍTICO (Capa de DataWarehouse)
CREATE USER PUKIO_DWH IDENTIFIED BY puk10_2024;
ALTER USER PUKIO_DWH DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE TO PUKIO_DWH;
GRANT CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO PUKIO_DWH;
ALTER USER PUKIO_DWH QUOTA UNLIMITED ON USERS;

-- 4. OTORGAR PERMISOS CRUZADOS (Para permitir lectura y carga ETL entre esquemas)
GRANT SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO PUKIO_DB;
GRANT SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO PUKIO_DWH;

COMMIT;
