-- ============================================================
-- PUKIO - Sistema POS
-- Script 01: Creacion de Tablas
-- Base de Datos: Oracle 21c XE
-- ============================================================

ALTER SESSION SET CURRENT_SCHEMA = PUKIO_DB;

-- Tabla de Usuarios
CREATE TABLE USUARIOS (
    ID_USUARIO    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME      VARCHAR2(50)  NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(100)  NOT NULL,
    NOMBRE        VARCHAR2(100) NOT NULL,
    ROL           VARCHAR2(20)  NOT NULL CHECK (ROL IN ('ADMIN','CAJERO')),
    ACTIVO        NUMBER(1)     DEFAULT 1 NOT NULL,
    FECHA_CREACION DATE         DEFAULT SYSDATE
);

-- Tabla de Categorias
CREATE TABLE CATEGORIAS (
    ID_CATEGORIA  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE        VARCHAR2(80)  NOT NULL UNIQUE,
    DESCRIPCION   VARCHAR2(200),
    ACTIVO        NUMBER(1)     DEFAULT 1 NOT NULL
);

-- Tabla de Proveedores
CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUC           VARCHAR2(20)  NOT NULL UNIQUE,
    NOMBRE        VARCHAR2(150) NOT NULL,
    CONTACTO      VARCHAR2(100),
    TELEFONO      VARCHAR2(20),
    CORREO        VARCHAR2(100),
    DIRECCION     VARCHAR2(200),
    ACTIVO        NUMBER(1)     DEFAULT 1 NOT NULL
);

-- Tabla de Productos
CREATE TABLE PRODUCTOS (
    ID_PRODUCTO   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO        VARCHAR2(30)   NOT NULL UNIQUE,
    NOMBRE        VARCHAR2(150)  NOT NULL,
    DESCRIPCION   VARCHAR2(300),
    PRECIO_COMPRA NUMBER(12,2)   DEFAULT 0 NOT NULL,
    PRECIO_VENTA  NUMBER(12,2)   NOT NULL,
    STOCK         NUMBER(10)     DEFAULT 0 NOT NULL,
    STOCK_MINIMO  NUMBER(10)     DEFAULT 5  NOT NULL,
    ID_CATEGORIA  NUMBER         REFERENCES CATEGORIAS(ID_CATEGORIA),
    ID_PROVEEDOR  NUMBER         REFERENCES PROVEEDORES(ID_PROVEEDOR),
    ACTIVO        NUMBER(1)      DEFAULT 1 NOT NULL,
    FECHA_REGISTRO DATE          DEFAULT SYSDATE
);

-- Tabla de Clientes
CREATE TABLE CLIENTES (
    ID_CLIENTE    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_DOC      VARCHAR2(10)  DEFAULT 'DNI' NOT NULL,
    NUMERO_DOC    VARCHAR2(20)  NOT NULL UNIQUE,
    NOMBRE        VARCHAR2(150) NOT NULL,
    TELEFONO      VARCHAR2(20),
    CORREO        VARCHAR2(100),
    DIRECCION     VARCHAR2(200),
    ACTIVO        NUMBER(1)     DEFAULT 1 NOT NULL,
    FECHA_REGISTRO DATE         DEFAULT SYSDATE
);

-- Tabla de Ventas (Cabecera)
CREATE TABLE VENTAS (
    ID_VENTA      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_COMPROBANTE VARCHAR2(20) NOT NULL UNIQUE,
    TIPO_COMPROBANTE   VARCHAR2(20) DEFAULT 'BOLETA' NOT NULL,
    ID_CLIENTE    NUMBER         REFERENCES CLIENTES(ID_CLIENTE),
    ID_USUARIO    NUMBER         NOT NULL REFERENCES USUARIOS(ID_USUARIO),
    FECHA_VENTA   DATE           DEFAULT SYSDATE NOT NULL,
    SUBTOTAL      NUMBER(12,2)   NOT NULL,
    IGV           NUMBER(12,2)   NOT NULL,
    DESCUENTO     NUMBER(12,2)   DEFAULT 0,
    TOTAL         NUMBER(12,2)   NOT NULL,
    METODO_PAGO   VARCHAR2(20)   DEFAULT 'EFECTIVO' NOT NULL,
    ESTADO        VARCHAR2(20)   DEFAULT 'COMPLETADA' NOT NULL
);

-- Tabla de Detalle de Venta
CREATE TABLE DETALLE_VENTA (
    ID_DETALLE    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VENTA      NUMBER         NOT NULL REFERENCES VENTAS(ID_VENTA),
    ID_PRODUCTO   NUMBER         NOT NULL REFERENCES PRODUCTOS(ID_PRODUCTO),
    CANTIDAD      NUMBER(10)     NOT NULL,
    PRECIO_UNIT   NUMBER(12,2)   NOT NULL,
    DESCUENTO     NUMBER(12,2)   DEFAULT 0,
    SUBTOTAL      NUMBER(12,2)   NOT NULL
);

-- Secuencia para numero de comprobante
CREATE SEQUENCE SEQ_COMPROBANTE START WITH 1 INCREMENT BY 1 NOCACHE;

-- Indices para busquedas frecuentes
CREATE INDEX IDX_PROD_CODIGO    ON PRODUCTOS(CODIGO);
CREATE INDEX IDX_PROD_NOMBRE    ON PRODUCTOS(NOMBRE);
CREATE INDEX IDX_CLI_NUMDOC     ON CLIENTES(NUMERO_DOC);
CREATE INDEX IDX_VENTA_FECHA    ON VENTAS(FECHA_VENTA);
CREATE INDEX IDX_DET_VENTA      ON DETALLE_VENTA(ID_VENTA);

COMMIT;
