-- ============================================================
-- PUKIO - Sistema POS
-- Script 03: Tablas DataWarehouse y OLAP
-- ============================================================

ALTER SESSION SET CURRENT_SCHEMA = PUKIO_DWH;

-- Tabla principal DataWarehouse de Ventas
CREATE TABLE DWH_VENTAS (
    ID_DWH          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VENTA        NUMBER         NOT NULL,
    NUMERO_COMPROBANTE VARCHAR2(20),
    TIPO_COMPROBANTE   VARCHAR2(20),
    FECHA_VENTA     DATE           NOT NULL,
    ANIO            NUMBER(4)      NOT NULL,
    MES             NUMBER(2)      NOT NULL,
    DIA             NUMBER(2)      NOT NULL,
    TRIMESTRE       NUMBER(1)      NOT NULL,
    NOMBRE_CLIENTE  VARCHAR2(150),
    NOMBRE_CAJERO   VARCHAR2(100),
    NOMBRE_PRODUCTO VARCHAR2(150)  NOT NULL,
    CATEGORIA       VARCHAR2(80),
    CANTIDAD        NUMBER(10)     NOT NULL,
    PRECIO_UNIT     NUMBER(12,2)   NOT NULL,
    SUBTOTAL        NUMBER(12,2)   NOT NULL,
    IGV             NUMBER(12,2),
    TOTAL_VENTA     NUMBER(12,2),
    METODO_PAGO     VARCHAR2(20),
    FECHA_CARGA     DATE           DEFAULT SYSDATE
);

-- Tabla CrossTab (Cubo OLAP): Ventas por Categoria y Mes
CREATE TABLE CROSSTAB_VENTAS (
    ID_CROSSTAB     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ANIO            NUMBER(4)      NOT NULL,
    MES             NUMBER(2)      NOT NULL,
    CATEGORIA       VARCHAR2(80)   NOT NULL,
    TOTAL_UNIDADES  NUMBER(12)     DEFAULT 0,
    TOTAL_INGRESOS  NUMBER(14,2)   DEFAULT 0,
    TOTAL_VENTAS    NUMBER(10)     DEFAULT 0,
    FECHA_GENERADO  DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_CT UNIQUE (ANIO, MES, CATEGORIA)
);

-- Vista para facilitar carga al DWH (Haciendo referencia cruzada al esquema PUKIO_DB)
CREATE OR REPLACE VIEW VW_VENTAS_DETALLADA AS
SELECT
    V.ID_VENTA,
    V.NUMERO_COMPROBANTE,
    V.TIPO_COMPROBANTE,
    V.FECHA_VENTA,
    EXTRACT(YEAR  FROM V.FECHA_VENTA) AS ANIO,
    EXTRACT(MONTH FROM V.FECHA_VENTA) AS MES,
    EXTRACT(DAY   FROM V.FECHA_VENTA) AS DIA,
    CEIL(EXTRACT(MONTH FROM V.FECHA_VENTA) / 3) AS TRIMESTRE,
    COALESCE(C.NOMBRE, 'GENERICO')    AS NOMBRE_CLIENTE,
    U.NOMBRE                           AS NOMBRE_CAJERO,
    P.NOMBRE                           AS NOMBRE_PRODUCTO,
    CAT.NOMBRE                         AS CATEGORIA,
    DV.CANTIDAD,
    DV.PRECIO_UNIT,
    DV.SUBTOTAL,
    V.IGV,
    V.TOTAL                            AS TOTAL_VENTA,
    V.METODO_PAGO
FROM PUKIO_DB.VENTAS V
JOIN PUKIO_DB.DETALLE_VENTA DV ON DV.ID_VENTA   = V.ID_VENTA
JOIN PUKIO_DB.PRODUCTOS P      ON P.ID_PRODUCTO = DV.ID_PRODUCTO
JOIN PUKIO_DB.USUARIOS U       ON U.ID_USUARIO  = V.ID_USUARIO
LEFT JOIN PUKIO_DB.CLIENTES C  ON C.ID_CLIENTE  = V.ID_CLIENTE
LEFT JOIN PUKIO_DB.CATEGORIAS CAT ON CAT.ID_CATEGORIA = P.ID_CATEGORIA;

COMMIT;
